Add key checking in development mode
LestaD/themz pull request #1
Opened 2017-10-02 15:00 UTC by yarastqt

2017-10-02 15:12 UTC, sergeysova requested changes

2017-10-02 15:12 UTC, LestaD commented on src/index.js
> +  pathOr('Unknown', ['children', '_owner', '_currentElement', 'type', 'displayName'], props)
Использование скрытых переменных инстансов не хорошая тема.
Нужно поискать варианты

2017-10-02 15:15 UTC, yarastqt commented on src/index.js
> +  pathOr('Unknown', ['children', '_owner', '_currentElement', 'type', 'displayName'], props)
Ваще не хорошая тема, но не знаю как лучше сделать. В recompose'e ты говорил есть хелпер, но он просто принимает компонент на вход и читает свойство displayName.

2017-10-02 15:29 UTC, sergeysova approved these changes

2017-10-02 15:29 UTC, LestaD commented
@yarastqt напиши тесты на эту штуку

2017-10-13 12:17 UTC, sergeysova requested changes

2017-10-13 12:17 UTC, LestaD commented on src/index.js
> +  const [, ...sections] = idx
может сделать проще так?

```js
const [, key, ...sections] = idx
```

2017-10-13 13:10 UTC, yarastqt commented on src/index.js
> +  const [, ...sections] = idx
Дак key у нас - это последний элемент, а в данном случае key будет вторым элементом

2017-10-13 13:32 UTC, LestaD commented on src/index.js
> +  const [, ...sections] = idx
Точно. Проглядел

2017-10-13 13:32 UTC, sergeysova approved these changes

2017-10-13 13:33 UTC, merged